name: Test Repository Secret

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret Availability
        env:
          MY_SECRET: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "Secret is NOT available!"
            exit 1
          else
            echo "Secret is available!"
          fi
